/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.panel;

import javax.swing.JOptionPane;
import ui.listener.BasicActionListener;
import ui.messages.ErrorMessage;

/**
 *
 * @author rodel
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        initPersonalInfoAddEditListener();
        initApplicantPersonalInfo();
        initEmploymentDataAddEditListener();
    }

    private void initApplicantPersonalInfo() {
        panelPersonalInfo.setFieldsToEditable(false);
        panelPersonalInfo.resetToDefault();
    }

    private void initPersonalInfoAddEditListener() {
        addEditPersonalInfo.setBasicActionListener(new BasicActionListener() {

            @Override
            public void onAdd() {
                panelPersonalInfo.setFieldsToEditable(true);
                panelPersonalInfo.resetToDefault();
            }

            @Override
            public boolean onSaveAdd() {
                boolean isSaved = panelPersonalInfo.savePersonalInfo();
                if (!isSaved) {
                    JOptionPane.showMessageDialog(null, ErrorMessage.FAILED_TO_INSERT, ErrorMessage.ERROR_MESSAGE_TITLE, JOptionPane.WARNING_MESSAGE);
                }
                return isSaved;
            }

            @Override
            public void onCancelAdd() {
                panelPersonalInfo.resetToDefault();
                panelPersonalInfo.setFieldsToEditable(false);
            }

            @Override
            public void onEdit() {
                panelPersonalInfo.setFieldsToEditable(true);
            }

            @Override
            public boolean onSaveEdit() {
                boolean isUpdated = panelPersonalInfo.updatePersonalInfo();
                 if (!isUpdated) {
                    JOptionPane.showMessageDialog(null, ErrorMessage.FAILED_TO_UPDATE, ErrorMessage.ERROR_MESSAGE_TITLE, JOptionPane.WARNING_MESSAGE);
                }
                return true;
            }

            @Override
            public void onCancelEdit() {
                panelPersonalInfo.setFieldsToEditable(false);
            }
        });
    }
    
    private void initEmploymentDataAddEditListener() {
        addEditEmployment.setBasicActionListener(new BasicActionListener() {

            @Override
            public void onAdd() {
                panelEmploymentData.setFieldsEditable(true);
                panelEmploymentData.resetToDefault();
            }

            @Override
            public boolean onSaveAdd() {
                boolean isSaved = panelEmploymentData.saveEmploymentData();
                if(!isSaved) {
                    JOptionPane.showMessageDialog(null, ErrorMessage.FAILED_TO_INSERT, ErrorMessage.ERROR_MESSAGE_TITLE, JOptionPane.WARNING_MESSAGE);
                }
                return isSaved;
            }

            @Override
            public void onCancelAdd() {
                panelEmploymentData.setFieldsEditable(false);
                panelEmploymentData.resetToDefault();
            }

            @Override
            public void onEdit() {
                panelEmploymentData.setFieldsEditable(true);
            }

            @Override
            public boolean onSaveEdit() {
//                boolean isUpdated = panelEmploymentData.up
                return true;
            }

            @Override
            public void onCancelEdit() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panelPersonalInfo = new ui.reusable.PersonalInformationPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panelEmploymentData = new ui.reusable.EmploymentDataPanel();
        addEditEmployment = new ui.reusable.AddEditButtonPanel();
        jPanel3 = new javax.swing.JPanel();
        familyBackgroundPanel1 = new ui.reusable.FamilyBackgroundPanel();
        addEditButtonPanel1 = new ui.reusable.AddEditButtonPanel();
        jPanel4 = new javax.swing.JPanel();
        siblingsPanel1 = new ui.reusable.SiblingsPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicle = new javax.swing.JTable();
        addEditButtonPanel3 = new ui.reusable.AddEditButtonPanel();
        jPanel5 = new javax.swing.JPanel();
        characterReferenceDependentPanel1 = new ui.reusable.CharacterReferenceDependentPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehicle1 = new javax.swing.JTable();
        addEditButtonPanel4 = new ui.reusable.AddEditButtonPanel();
        jPanel6 = new javax.swing.JPanel();
        characterReferenceDependentPanel2 = new ui.reusable.CharacterReferenceDependentPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVehicle2 = new javax.swing.JTable();
        addEditButtonPanel5 = new ui.reusable.AddEditButtonPanel();
        jPanel7 = new javax.swing.JPanel();
        creditReferencePanel1 = new ui.reusable.CreditReferencePanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblVehicle3 = new javax.swing.JTable();
        addEditButtonPanel6 = new ui.reusable.AddEditButtonPanel();
        jPanel8 = new javax.swing.JPanel();
        sourceOfIncomePanel1 = new ui.reusable.SourceOfIncomePanel();
        addEditButtonPanel7 = new ui.reusable.AddEditButtonPanel();
        jPanel9 = new javax.swing.JPanel();
        expendituresPanel1 = new ui.reusable.ExpendituresPanel();
        addEditButtonPanel8 = new ui.reusable.AddEditButtonPanel();
        jPanel10 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        landPanel1 = new ui.reusable.LandPanel();
        addEditButtonPanel9 = new ui.reusable.AddEditButtonPanel();
        jPanel12 = new javax.swing.JPanel();
        vehiclePanel1 = new ui.reusable.VehiclePanel();
        addEditButtonPanel10 = new ui.reusable.AddEditButtonPanel();
        jPanel13 = new javax.swing.JPanel();
        appliancesPanel1 = new ui.reusable.AppliancesPanel();
        addEditButtonPanel11 = new ui.reusable.AddEditButtonPanel();
        jPanel14 = new javax.swing.JPanel();
        machineryPanel1 = new ui.reusable.MachineryPanel();
        addEditButtonPanel12 = new ui.reusable.AddEditButtonPanel();
        addEditPersonalInfo = new ui.reusable.AddEditButtonPanel();
        jPanel15 = new javax.swing.JPanel();
        personalInformationPanel2 = new ui.reusable.PersonalInformationPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel16 = new javax.swing.JPanel();
        employmentDataPanel2 = new ui.reusable.EmploymentDataPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        familyBackgroundPanel2 = new ui.reusable.FamilyBackgroundPanel();
        jLabel16 = new javax.swing.JLabel();
        addEditButtonPanel13 = new ui.reusable.AddEditButtonPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblVehicle4 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        personalInformationPanel3 = new ui.reusable.PersonalInformationPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        employmentDataPanel3 = new ui.reusable.EmploymentDataPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        familyBackgroundPanel3 = new ui.reusable.FamilyBackgroundPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        sourceOfIncomePanel2 = new ui.reusable.SourceOfIncomePanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel24 = new javax.swing.JPanel();
        personalInformationPanel4 = new ui.reusable.PersonalInformationPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        employmentDataPanel4 = new ui.reusable.EmploymentDataPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        familyBackgroundPanel4 = new ui.reusable.FamilyBackgroundPanel();
        jLabel24 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panelPersonalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 5, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(panelEmploymentData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
        jPanel2.add(addEditEmployment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 215, -1, -1));

        jTabbedPane1.addTab("Employment", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(familyBackgroundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
        jPanel3.add(addEditButtonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 165, -1, -1));

        jTabbedPane1.addTab("Family", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(siblingsPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        tblVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type/Model", "Years Used", "Use", "Estimated Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVehicle);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 600, 90));
        jPanel4.add(addEditButtonPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 185, -1, -1));

        jTabbedPane1.addTab("Siblings", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(characterReferenceDependentPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        tblVehicle1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type/Model", "Years Used", "Use", "Estimated Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVehicle1);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 600, 90));
        jPanel5.add(addEditButtonPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 215, -1, -1));

        jTabbedPane1.addTab("Character Reference", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(characterReferenceDependentPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        tblVehicle2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type/Model", "Years Used", "Use", "Estimated Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblVehicle2);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 600, 90));
        jPanel6.add(addEditButtonPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 215, -1, -1));

        jTabbedPane1.addTab("Dependents", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(creditReferencePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        tblVehicle3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type/Model", "Years Used", "Use", "Estimated Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblVehicle3);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 600, 90));
        jPanel7.add(addEditButtonPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 215, -1, -1));

        jTabbedPane1.addTab("Credit Reference", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(sourceOfIncomePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
        jPanel8.add(addEditButtonPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        jTabbedPane1.addTab("Src. of Income", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(expendituresPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
        jPanel9.add(addEditButtonPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        jTabbedPane1.addTab("Expenditures", jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(landPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
        jPanel11.add(addEditButtonPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 215, -1, -1));

        jTabbedPane2.addTab("Land", jPanel11);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(vehiclePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
        jPanel12.add(addEditButtonPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 215, -1, -1));

        jTabbedPane2.addTab("Vehicle", jPanel12);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(appliancesPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
        jPanel13.add(addEditButtonPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 215, -1, -1));

        jTabbedPane2.addTab("Appliances", jPanel13);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(machineryPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
        jPanel14.add(addEditButtonPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 235, -1, -1));

        jTabbedPane2.addTab("Machinery", jPanel14);

        jPanel10.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 290));

        jTabbedPane1.addTab("Assets", jPanel10);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 235, 1020, 330));
        jPanel1.add(addEditPersonalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, -1, -1));

        tabMain.addTab("Applicant Personal Information", jPanel1);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(personalInformationPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(employmentDataPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jLabel15.setText("<-- Place Buttons Here -->");
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jTabbedPane3.addTab("Employment", jPanel16);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(familyBackgroundPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jLabel16.setText("<-- Place Buttons Here -->");
        jPanel17.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jTabbedPane3.addTab("Family", jPanel17);

        jPanel15.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 235, 1020, 330));
        jPanel15.add(addEditButtonPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, -1, -1));

        tabMain.addTab("Spouse Information", jPanel15);

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVehicle4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type/Model", "Years Used", "Use", "Estimated Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblVehicle4);

        jPanel18.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1000, 70));

        jLabel17.setText("<-- Place Buttons Here -->");
        jPanel18.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 85, -1, -1));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel19.add(personalInformationPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 5, -1, -1));

        jLabel18.setText("<-- Place Buttons Here -->");
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jTabbedPane4.addTab("Personal Info", jPanel19);

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel20.add(employmentDataPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jLabel19.setText("<-- Place Buttons Here -->");
        jPanel20.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jTabbedPane4.addTab("Employment", jPanel20);

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(familyBackgroundPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jLabel20.setText("<-- Place Buttons Here -->");
        jPanel21.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jTabbedPane4.addTab("Family", jPanel21);

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel22.add(sourceOfIncomePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jLabel21.setText("<-- Place Buttons Here -->");
        jPanel22.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jTabbedPane4.addTab("Source of Income", jPanel22);

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane5.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel24.add(personalInformationPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, 5, -1, -1));

        jLabel22.setText("<-- Place Buttons Here -->");
        jPanel24.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jTabbedPane5.addTab("Personal Info", jPanel24);

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel25.add(employmentDataPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jLabel23.setText("<-- Place Buttons Here -->");
        jPanel25.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jTabbedPane5.addTab("Employment", jPanel25);

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel26.add(familyBackgroundPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jLabel24.setText("<-- Place Buttons Here -->");
        jPanel26.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jTabbedPane5.addTab("Family", jPanel26);

        jPanel23.add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 400));

        jTabbedPane4.addTab("Spouse Information", jPanel23);

        jPanel18.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1030, 440));

        tabMain.addTab("Co-Maker", jPanel18);

        add(tabMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1040, 600));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.reusable.AddEditButtonPanel addEditButtonPanel1;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel10;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel11;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel12;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel13;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel3;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel4;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel5;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel6;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel7;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel8;
    private ui.reusable.AddEditButtonPanel addEditButtonPanel9;
    private ui.reusable.AddEditButtonPanel addEditEmployment;
    private ui.reusable.AddEditButtonPanel addEditPersonalInfo;
    private ui.reusable.AppliancesPanel appliancesPanel1;
    private ui.reusable.CharacterReferenceDependentPanel characterReferenceDependentPanel1;
    private ui.reusable.CharacterReferenceDependentPanel characterReferenceDependentPanel2;
    private ui.reusable.CreditReferencePanel creditReferencePanel1;
    private ui.reusable.EmploymentDataPanel employmentDataPanel2;
    private ui.reusable.EmploymentDataPanel employmentDataPanel3;
    private ui.reusable.EmploymentDataPanel employmentDataPanel4;
    private ui.reusable.ExpendituresPanel expendituresPanel1;
    private ui.reusable.FamilyBackgroundPanel familyBackgroundPanel1;
    private ui.reusable.FamilyBackgroundPanel familyBackgroundPanel2;
    private ui.reusable.FamilyBackgroundPanel familyBackgroundPanel3;
    private ui.reusable.FamilyBackgroundPanel familyBackgroundPanel4;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private ui.reusable.LandPanel landPanel1;
    private ui.reusable.MachineryPanel machineryPanel1;
    private ui.reusable.EmploymentDataPanel panelEmploymentData;
    private ui.reusable.PersonalInformationPanel panelPersonalInfo;
    private ui.reusable.PersonalInformationPanel personalInformationPanel2;
    private ui.reusable.PersonalInformationPanel personalInformationPanel3;
    private ui.reusable.PersonalInformationPanel personalInformationPanel4;
    private ui.reusable.SiblingsPanel siblingsPanel1;
    private ui.reusable.SourceOfIncomePanel sourceOfIncomePanel1;
    private ui.reusable.SourceOfIncomePanel sourceOfIncomePanel2;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTable tblVehicle;
    private javax.swing.JTable tblVehicle1;
    private javax.swing.JTable tblVehicle2;
    private javax.swing.JTable tblVehicle3;
    private javax.swing.JTable tblVehicle4;
    private ui.reusable.VehiclePanel vehiclePanel1;
    // End of variables declaration//GEN-END:variables
}
