/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.reusable;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author rodel
 */
public class FamilyBackgroundPanel extends javax.swing.JPanel implements KeyListener {

    /**
     * Creates new form FamilyBackgroundPanel
     */
    public FamilyBackgroundPanel() {
        initComponents();
        initTextBoxListener();
    }

    /**
     * Set Textbox Listener
     */
    private void initTextBoxListener() {
        txtFatherName.addKeyListener(this);
        txtFatherAddress.addKeyListener(this);
        txtFatherOccupation.addKeyListener(this);
        txtFatherBirthDate.addKeyListener(this);
        txtMotherName.addKeyListener(this);
        txtMotherAddress.addKeyListener(this);
        txtMotherOccupation.addKeyListener(this);
        txtMotherBirthDate.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtFatherAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFatherOccupation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMotherAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMotherOccupation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFatherBirthDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMotherBirthDate = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Father's Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

        txtFatherAddress.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtFatherAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 385, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Address");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 35, -1, -1));

        txtFatherOccupation.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtFatherOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 55, 160, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Occupation");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, -1, -1));

        txtFatherName.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 5, 385, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Mother's Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, -1, -1));

        txtMotherAddress.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtMotherAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 105, 385, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Address");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, -1, -1));

        txtMotherOccupation.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtMotherOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("Occupation");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 135, -1, -1));

        txtMotherName.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtMotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 385, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("BirthDate");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        txtFatherBirthDate.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtFatherBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 55, 130, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("BirthDate");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 135, -1, -1));

        txtMotherBirthDate.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtMotherBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 130, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFatherAddress;
    private javax.swing.JTextField txtFatherBirthDate;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtFatherOccupation;
    private javax.swing.JTextField txtMotherAddress;
    private javax.swing.JTextField txtMotherBirthDate;
    private javax.swing.JTextField txtMotherName;
    private javax.swing.JTextField txtMotherOccupation;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (txtFatherName.isFocusOwner()) {
                txtFatherAddress.requestFocus();
            } else if (txtFatherAddress.isFocusOwner()) {
                txtFatherOccupation.requestFocus();
            } else if (txtFatherOccupation.isFocusOwner()) {
                txtFatherBirthDate.requestFocus();
            } else if (txtFatherBirthDate.isFocusOwner()) {
                txtMotherName.requestFocus();
            } else if (txtMotherName.isFocusOwner()) {
                txtMotherAddress.requestFocus();
            } else if (txtMotherAddress.isFocusOwner()) {
                txtMotherOccupation.requestFocus();
            } else if (txtMotherOccupation.isFocusOwner()) {
                txtMotherBirthDate.requestFocus();
            }
                break;
            case KeyEvent.VK_UP:
                if (txtMotherBirthDate.isFocusOwner()) {
                txtMotherOccupation.requestFocus();
            } else if (txtMotherOccupation.isFocusOwner()) {
                txtMotherAddress.requestFocus();
            } else if (txtMotherAddress.isFocusOwner()) {
                txtMotherName.requestFocus();
            } else if (txtMotherName.isFocusOwner()) {
                txtFatherBirthDate.requestFocus();
            } else if (txtFatherBirthDate.isFocusOwner()) {
                txtFatherOccupation.requestFocus();
            } else if (txtFatherOccupation.isFocusOwner()) {
                txtFatherAddress.requestFocus();
            } else if (txtFatherAddress.isFocusOwner()) {
                txtFatherName.requestFocus();
            }
                break;
        }
    }
}
