/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.reusable;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author rodel
 */
public class SiblingsPanel extends javax.swing.JPanel implements KeyListener {

    /**
     * Creates new form SiblingsPanel
     */
    public SiblingsPanel() {
        initComponents();
        initTextBoxesListener();
    }
    
    /**
     * Set TextBox Listener
     */
    private void initTextBoxesListener() {
        txtSiblingName.addKeyListener(this);
        txtSiblingAddress.addKeyListener(this);
        txtSiblingContact.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSiblingName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSiblingAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSiblingContact = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

        txtSiblingName.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtSiblingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 5, 255, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Address");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 35, -1, -1));

        txtSiblingAddress.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtSiblingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 30, 255, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Contact");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, -1, -1));

        txtSiblingContact.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtSiblingContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 55, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtSiblingAddress;
    private javax.swing.JTextField txtSiblingContact;
    private javax.swing.JTextField txtSiblingName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (txtSiblingName.isFocusOwner()) {
                txtSiblingAddress.requestFocus();
            } else if (txtSiblingAddress.isFocusOwner()) {
                txtSiblingContact.requestFocus();
            }
                break;
            case KeyEvent.VK_UP:
                if (txtSiblingContact.isFocusOwner()) {
                txtSiblingAddress.requestFocus();
            } else if (txtSiblingAddress.isFocusOwner()) {
                txtSiblingName.requestFocus();
            }
                break;
        }
    }
}
